# Generated by Django 3.2 on 2021-05-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(help_text='Пример: 1234 567890', max_length=12, verbose_name='Паспортные данные')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_certificate', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Сертификат')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Профессия')),
                ('home', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['profession', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('clients', models.ManyToManyField(to='main.ClientProfile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacherprofile')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=2, verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время проведения')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.style', verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['weekday', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientprofile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['payment_date'],
                'get_latest_by': 'payment_date',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client'], name='main_paymen_client__8f05de_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='main_client_user_id_75fee7_idx'),
        ),
    ]
